# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NWVjYjMxNjI3NzgxM2JkNzc4YjYwYjhiN2QyOGJhMmM4YWEyNTQyYjA5Yzk4N2UwYjYxMzA5OTAwNGQyZjNlYWU4MDc3NzI0NDk3Y2ZjOGQ3YmM1YmM3NGFjOWQ3YTQzYjA4MjVkOTlmNzI2ZDU3MmY0NTM4ZjRmYmQ5YmRkYjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
